# -*- coding: utf-8 -*-
"""svm_med.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HtiV-HxH1hpnX_9EGjwCUhTIdzQUyjFX
"""

from sklearn.svm import SVC
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, accuracy_score

df = pd.read_csv('No-show-Issue-Comma-300k.csv')
df = df.fillna(0)

df.Gender.replace(('F', 'M'),('1', '0'), inplace=True)

df.Status.replace(('Show-Up', 'No-Show'),('1', '0'), inplace=True)

df.DayOfTheWeek.replace(('Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'),('0', '1', '2', '3', '4', '5', '6'), inplace=True)

del df['ApointmentData']
del df['AppointmentRegistration']

X = df[list(df.columns)[2:]]
Y = df['AwaitingTime']

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.20,random_state=46)

regressor=SVC(C=1.0, kernel="linear",gamma="auto")

regressor.fit(X_train,Y_train)

y_prediction = regressor.predict(X_test)

print(y_prediction)
print(regressor.fit(X_test, Y_test))
print(accuracy_score(y_prediction, Y_test))
print(classification_report(y_prediction, Y_test))